# --- pyproject.toml | checksum: auto ---
[tool.ruff]
line-length = 320
indent-width = 2

[tool.ruff.lint]
select = ["e", "f", "w", "era"]
ignore = ["e401", "e701", "e501", "f401", "e722", "e741", "w291", "w292", "w293"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"